import argparse
import asyncio
import json
import math
import os
import sys

from ._version import __version__
from .engine import Josty
from .models import SearchResult
from .status import SearchStatus


def parser() -> argparse.ArgumentParser:
    command = argparse.ArgumentParser(
        description="Small, auditable metasearch for AI agents"
    )
    command.add_argument(
        "--version",
        action="version",
        version=f"josty {__version__}",
        help="print the version and exit",
    )
    command.add_argument(
        "query", nargs="?", default="", help="search query (not needed with --diagnose)"
    )
    command.add_argument("--limit", type=int, default=10)
    command.add_argument("--site", action="append", dest="sites", help="add a site: filter")
    command.add_argument("--mode", choices=("plain", "exact", "oss"), default="plain")
    command.add_argument("--category", choices=("text", "news"), default="text")
    command.add_argument("--region", help="DDGS region code, for example us-en or de-de")
    command.add_argument(
        "--safe-search", choices=("on", "moderate", "off"), default="moderate"
    )
    command.add_argument(
        "--time-limit", choices=("d", "w", "m", "y"), help="day, week, month, or year"
    )
    command.add_argument(
        "--profile",
        choices=("general", "dev"),
        default="general",
        help="ranking profile boosting dev domains (default: %(default)s)",
    )
    command.add_argument("--fetch", action="store_true", help="extract bounded text from results")
    command.add_argument(
        "--github", action="store_true", help="also search official GitHub repositories"
    )
    command.add_argument(
        "--results-only", action="store_true", help="emit only the result array"
    )
    command.add_argument(
        "--diagnose",
        action="store_true",
        help="probe HTTPS homepage reachability (transport only; not search health)",
    )
    command.add_argument(
        "--no-cache", action="store_true", help="bypass local disk cache"
    )
    command.add_argument(
        "--clear-cache", action="store_true", help="clear cached search results and exit"
    )
    command.add_argument(
        "--cache-stats", action="store_true", help="print local cache statistics and exit"
    )
    command.add_argument(
        "--max-query-variants",
        type=int,
        default=None,
        help="cap maximum query variants generated by mode and site expansion",
    )
    command.add_argument(
        "--search-concurrency",
        type=int,
        default=Josty.DEFAULT_SEARCH_CONCURRENCY,
        help="max concurrent search backend requests (default: %(default)d)",
    )
    command.add_argument(
        "--fetch-concurrency",
        type=int,
        default=Josty.DEFAULT_FETCH_CONCURRENCY,
        help="max concurrent page fetches (default: %(default)d)",
    )
    command.add_argument(
        "--max-content-chars",
        type=int,
        default=Josty.DEFAULT_MAX_CONTENT_CHARS,
        help="cap extracted markdown length per page (default: %(default)d, 0 for unlimited)",
    )
    return command


def fetch_parser() -> argparse.ArgumentParser:
    cmd = argparse.ArgumentParser(
        description="Extract bounded text from URLs or piped Josty search results"
    )
    cmd.add_argument("urls", nargs="*", help="target URLs to fetch")
    cmd.add_argument(
        "--stdin", action="store_true", help="read URLs or SearchRun JSON from stdin"
    )
    cmd.add_argument(
        "--fetch-concurrency",
        type=int,
        default=Josty.DEFAULT_FETCH_CONCURRENCY,
        help="max concurrent page fetches (default: %(default)d)",
    )
    cmd.add_argument(
        "--max-content-chars",
        type=int,
        default=Josty.DEFAULT_MAX_CONTENT_CHARS,
        help="cap extracted markdown length per page (default: %(default)d, 0 for unlimited)",
    )
    cmd.add_argument(
        "--limit",
        type=int,
        default=None,
        help="max number of results to fetch",
    )
    return cmd


async def run_fetch(args: argparse.Namespace) -> dict | list:
    raw_input = ""
    if args.stdin:
        raw_input = sys.stdin.read().strip()
    urls = list(args.urls)

    engine = Josty(
        max_fetch_concurrency=args.fetch_concurrency,
        max_content_chars=args.max_content_chars,
        enable_cache=False,
    )

    if raw_input.startswith("{"):
        try:
            payload = json.loads(raw_input)
            if isinstance(payload, dict) and "results" in payload:
                results_raw = payload.get("results", [])
                if args.limit is not None and args.limit > 0:
                    results_raw = results_raw[: args.limit]
                items = [
                    SearchResult(
                        title=r.get("title", ""),
                        url=r.get("url", ""),
                        snippet=r.get("snippet", ""),
                        sources=r.get("sources", []),
                        published_at=r.get("published_at"),
                        publisher=r.get("publisher"),
                        score=r.get("score", 0.0),
                        content=r.get("content"),
                        extraction_method=r.get("extraction_method"),
                        fetched_url=r.get("fetched_url"),
                        fetched_at=r.get("fetched_at"),
                        fetch_error=r.get("fetch_error"),
                        engine_ranks=r.get("engine_ranks", {}),
                        rank_contributions=r.get("rank_contributions", {}),
                        score_weights=r.get("score_weights", {}),
                    )
                    for r in results_raw
                    if isinstance(r, dict) and r.get("url")
                ]
                await engine.fetch_content(items)
                payload["results"] = [item.dict() for item in items]
                ok_count = sum(1 for item in items if item.content is not None)
                fail_count = sum(1 for item in items if item.fetch_error is not None)
                payload["fetch_requested"] = True
                payload["fetch_attempted"] = len(items)
                payload["fetch_ok"] = ok_count
                payload["fetch_failed"] = fail_count
                status_str = (
                    "noop"
                    if len(items) == 0
                    else (
                        "complete"
                        if fail_count == 0
                        else ("failed" if ok_count == 0 else "degraded")
                    )
                )
                payload["fetch"] = {
                    "requested": True,
                    "attempted": len(items),
                    "ok": ok_count,
                    "failed": fail_count,
                    "status": status_str,
                }
                if fail_count > 0 and payload.get("status") == SearchStatus.COMPLETE:
                    payload["status"] = SearchStatus.DEGRADED
                return payload
        except json.JSONDecodeError:
            pass

    # Plain text URLs from stdin or arguments
    if raw_input and not urls:
        urls = [line.strip() for line in raw_input.splitlines() if line.strip()]

    if not urls:
        raise ValueError("no URLs provided to fetch (supply URLs as arguments or pass --stdin)")

    if args.limit is not None and args.limit > 0:
        urls = urls[: args.limit]

    items = [SearchResult(title="", url=u, snippet="") for u in urls]
    await engine.fetch_content(items)
    return [
        {
            "url": item.url,
            "content": item.content,
            "extraction_method": item.extraction_method,
            "fetched_url": item.fetched_url,
            "fetched_at": item.fetched_at,
            "fetch_error": item.fetch_error,
        }
        for item in items
    ]


async def run(args: argparse.Namespace) -> dict | list:
    engine = Josty(
        github_token=os.getenv("GITHUB_TOKEN"),
        max_search_concurrency=args.search_concurrency,
        max_fetch_concurrency=args.fetch_concurrency,
        max_content_chars=args.max_content_chars,
        max_query_variants=args.max_query_variants,
        profile=args.profile,
        enable_cache=not args.no_cache,
    )
    if args.diagnose:
        return (
            await engine.diagnose_run(include_github=args.github, category=args.category)
        ).dict()
    search = await engine.research_run(
        args.query,
        sites=args.sites,
        mode=args.mode,
        limit=args.limit,
        fetch=args.fetch,
        include_github=args.github,
        category=args.category,
        region=args.region,
        safesearch=args.safe_search,
        timelimit=args.time_limit,
        profile=args.profile,
        max_query_variants=args.max_query_variants,
    )
    return [item.dict() for item in search.results] if args.results_only else search.dict()


def _sanitize_json(value: object) -> object:
    """Replace non-finite floats with None so one NaN field cannot fail the query."""
    if isinstance(value, float) and not math.isfinite(value):
        return None
    if isinstance(value, dict):
        return {key: _sanitize_json(item) for key, item in value.items()}
    if isinstance(value, list):
        return [_sanitize_json(item) for item in value]
    return value


def main(argv: list[str] | None = None) -> None:
    if argv is None:
        argv = sys.argv[1:]

    if argv and argv[0] == "fetch":
        fparser = fetch_parser()
        fargs = fparser.parse_args(argv[1:])
        if not fargs.stdin and not fargs.urls:
            fparser.error("must provide target URLs or pass --stdin")
        try:
            payload = asyncio.run(run_fetch(fargs))
            print(
                json.dumps(
                    _sanitize_json(payload),
                    ensure_ascii=False,
                    indent=2,
                    allow_nan=False,
                )
            )
            return
        except (ValueError, KeyboardInterrupt) as exc:
            print(json.dumps({"error": str(exc)}), file=sys.stderr)
            raise SystemExit(2) from exc

    if argv and argv[0] == "search":
        argv = argv[1:]

    command = parser()
    args = command.parse_args(argv)
    if args.clear_cache:
        Josty().clear_cache()
        print(json.dumps({"status": "cleared", "message": "Search cache cleared"}))
        return
    if args.cache_stats:
        print(json.dumps(Josty().cache_stats(), indent=2))
        return
    if not args.query and not args.diagnose:
        command.error(
            "a query is required unless --diagnose, --clear-cache, or --cache-stats is given"
        )
    if args.diagnose and args.results_only:
        command.error("--results-only cannot be combined with --diagnose")
    try:
        payload = asyncio.run(run(args))
        # allow_nan=False keeps stdout strictly RFC-8259 JSON. Non-finite
        # floats are sanitized to null first so one bad field degrades in-band
        # instead of exiting 2 for the whole query.
        print(
            json.dumps(
                _sanitize_json(payload),
                ensure_ascii=False,
                indent=2,
                allow_nan=False,
            )
        )
        # Exit-code contract (#42): only a search envelope that failed outright
        # exits 1. complete/degraded/empty searches exit 0 so callers read the
        # in-band status; JSON stays on stdout in every search case. Diagnose is
        # a transport probe with its own status and keeps exit 0.
        if (
            not args.diagnose
            and isinstance(payload, dict)
            and payload.get("status") == SearchStatus.FAILED
        ):
            raise SystemExit(1)
    except (ValueError, KeyboardInterrupt) as exc:
        print(json.dumps({"error": str(exc)}), file=sys.stderr)
        raise SystemExit(2) from exc


if __name__ == "__main__":
    main()
