import argparse
import asyncio
import json
import os
import sys

from .engine import Josty


def parser() -> argparse.ArgumentParser:
    command = argparse.ArgumentParser(
        description="Small, auditable metasearch for AI agents"
    )
    command.add_argument(
        "query", nargs="?", default="", help="search query (not needed with --diagnose)"
    )
    command.add_argument("--limit", type=int, default=10)
    command.add_argument("--site", action="append", dest="sites", help="add a site: filter")
    command.add_argument("--mode", choices=("plain", "exact", "oss"), default="plain")
    command.add_argument("--category", choices=("text", "news"), default="text")
    command.add_argument("--region", help="DDGS region code, for example us-en or de-de")
    command.add_argument(
        "--safe-search", choices=("on", "moderate", "off"), default="moderate"
    )
    command.add_argument(
        "--time-limit", choices=("d", "w", "m", "y"), help="day, week, month, or year"
    )
    command.add_argument(
        "--profile",
        choices=("general", "dev", "academic"),
        default="general",
        help="ranking profile boosting dev/academic domains (default: %(default)s)",
    )
    command.add_argument("--fetch", action="store_true", help="extract bounded text from results")
    command.add_argument(
        "--github", action="store_true", help="also search official GitHub repositories"
    )
    command.add_argument(
        "--results-only", action="store_true", help="emit only the result array"
    )
    command.add_argument(
        "--diagnose",
        action="store_true",
        help="probe backend host reachability instead of searching",
    )
    command.add_argument(
        "--no-cache", action="store_true", help="bypass local disk cache"
    )
    command.add_argument(
        "--clear-cache", action="store_true", help="clear cached search results and exit"
    )
    command.add_argument(
        "--cache-stats", action="store_true", help="print local cache statistics and exit"
    )
    command.add_argument(
        "--max-query-variants",
        type=int,
        default=None,
        help="cap maximum query variants generated by mode and site expansion",
    )
    command.add_argument(
        "--search-concurrency",
        type=int,
        default=Josty.DEFAULT_SEARCH_CONCURRENCY,
        help="max concurrent search backend requests (default: %(default)d)",
    )
    command.add_argument(
        "--fetch-concurrency",
        type=int,
        default=Josty.DEFAULT_FETCH_CONCURRENCY,
        help="max concurrent page fetches (default: %(default)d)",
    )
    command.add_argument(
        "--max-content-chars",
        type=int,
        default=8000,
        help="cap extracted markdown length per page (default: %(default)d, 0 for unlimited)",
    )
    return command


async def run(args: argparse.Namespace) -> dict | list:
    engine = Josty(
        github_token=os.getenv("GITHUB_TOKEN"),
        max_search_concurrency=args.search_concurrency,
        max_fetch_concurrency=args.fetch_concurrency,
        max_content_chars=args.max_content_chars,
        max_query_variants=args.max_query_variants,
        profile=args.profile,
        enable_cache=not args.no_cache,
    )
    if args.diagnose:
        return (
            await engine.diagnose_run(include_github=args.github, category=args.category)
        ).dict()
    search = await engine.research_run(
        args.query,
        sites=args.sites,
        mode=args.mode,
        limit=args.limit,
        fetch=args.fetch,
        include_github=args.github,
        category=args.category,
        region=args.region,
        safesearch=args.safe_search,
        timelimit=args.time_limit,
        profile=args.profile,
        max_query_variants=args.max_query_variants,
    )
    return [item.dict() for item in search.results] if args.results_only else search.dict()


def main() -> None:
    command = parser()
    args = command.parse_args()
    if args.clear_cache:
        Josty().clear_cache()
        print(json.dumps({"status": "cleared", "message": "Search cache cleared"}))
        return
    if args.cache_stats:
        print(json.dumps(Josty().cache_stats(), indent=2))
        return
    if not args.query and not args.diagnose:
        command.error(
            "a query is required unless --diagnose, --clear-cache, or --cache-stats is given"
        )
    if args.diagnose and args.results_only:
        command.error("--results-only cannot be combined with --diagnose")
    try:
        payload = asyncio.run(run(args))
    except (ValueError, KeyboardInterrupt) as exc:
        print(json.dumps({"error": str(exc)}), file=sys.stderr)
        raise SystemExit(2) from exc
    print(json.dumps(payload, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
